'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('periodicals').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('periodicals').insert({
          id: 1,
          name: 'Conjunctions',
          issue: 'Sleights of Hand: The Deception Issue (Conjunctions Book 65)',
          editor: 'Bradford Morrow',
          editor_url: 'https://images.gr-assets.com/authors/1297526247p8/25383.jpg',
          edition: 'Kindle Edition',
          publication_date: '2016-02-23 0:00:01 UTC',
          pages: 409,
          img_url: 'https://images.gr-assets.com/books/1469914184l/31298794.jpg',
          description: "Children deceive, as do grownups, and many are the moments when all of us even deceive ourselves. People of every age and stripe, whether rarely or often, dissimulate, bluff, and beguile. The writer who fabricates and populates worlds is a deceiver, as is the artist whose triumph is to trick the eye, to alter perception. The honest magician's livelihood is based on deception; so is the dishonest thief's. And consider the great Russian poet Marina Tsvetaeva who wrote, \"A deception that elevates us is dearer than a legion of low truths,\" thus complicating the subject entirely. This special issue of Conjunctions gathers a wide spectrum of essays, fiction, and poetry on the classic subject of deception, exploring in original and thought-provoking ways a world in which truth is a most fragile, elaborate, and mercurial thing. Contributors include Edie Meidav, Terese Svoboda, Yannick Murphy, Paul Hoover, Bim Ramke, Eleni Sikelianos, Magdalena Zyzak, and many others.",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 2,
          name: 'Asimov\'s Science Fiction',
          issue: 'October/November 2016 (Asimov\'s Science Fiction #489-490)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2016-09-23 0:00:01 UTC',
          pages: 196,
          img_url: 'https://images.gr-assets.com/books/1474637247l/32186440.jpg',
          description: "Novella\n \"The Forgotten Taste of Honey\" by Alexander Jablokov\n \"Choose Poison, Choose Life\" by Michael Blumlein\n Novelettes\n \"Eating Science with Ghosts\" by Octavia Cade\n \"Wretched the Romantic\" by Michael Libling\n \"The Leaning Lincoln\" by Will Ludwigsen\n \"Project Entropy\" by Dominca Phetteplace\n Short Stories\n \"The People in the Building\" by Sandra McDonald\n \"Water Scorpions\" by Rich Larson\n \"Lucite\" by Susan Palwick\n \"When Grandfather Returns\" by S. N. Dyer\n Asimov's Volume 40, No. 10&11 (#489&490) October-November 2016\n Sheila Williams, editor\n Cover art by Karla Oritz",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 3,
          name: 'One Story',
          issue: 'Issue #222 - "The Quality of Your Life" by Min Jin Lee',
          editor: 'Hannah Tinti',
          editor_url: 'http://cwp.as.nyu.edu/props/IO/35476/42/hannahtinti.jpg',
          edition: 'Kindle Edition',
          publication_date: '2016-11-23 0:00:01 UTC',
          pages: 36,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2016/11/222_cover.png',
          description: "When we’re young, we tend to be idealistic. Everything is new and exciting—especially when it comes to love. A heart that has never been broken before is easier to give away. We do it without knowing the danger. We offer it with both hands. This kind of blind, joyous affection is beautifully captured in our new issue, Min Jin Lee’s \“The Quality of Your Life.\” Set in Korea in 1932, the story follows Sunja, a girl on the cusp of womanhood. Her days are filled with hard work and shopping at the daily market for the boarding house run by her mother. And then, in an instant, everything changes. Sunja crosses paths with an older man named Hansu, who travels for business between Korea and Japan. Soon the blossoming relationship between these two characters becomes as complicated and fraught as the relationship between those two nations. Sunja struggles to maintain her identity, just as her fellow Koreans work against the historical ties that bind them to Japan. This theme continues in Min Jin Lee’s forthcoming novel, Pachinko. Find out more in our Q&A, and then continue on Sunja’s epic journey, where she never gives up fighting for the people she loves.",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 4,
          name: 'Asimov\'s Science Fiction',
          issue: 'December 2016 (Asimov\'s Science Fiction #491)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2016-11-09 0:00:01 UTC',
          pages: 115,
          img_url: 'https://images.gr-assets.com/books/1480011299l/33121057.jpg',
          description: "Novella\n \"Where There Is Nothing, There Is God\" by David Erik Nelson\n Novelettes\n \"They Have All One Breath\" by Karl Bunker\n \"Empty Shoes by the Lake\" by Gay Partington Terry\n \"HigherWorks\" by Gregory Norman Bossert\n Short Stories\n \"How the Damned Live On\" by James Sallis\n \"The Cold Side of the Island\" by Kali Wallace\n Poetry\n \"Million-Year Elegies: Archaeopteryx\" by Ada Hoffmann\n \"Relativistic Dickinson\" by John Richard Trtek\n Asimov's Volume 40, No. 12 (#491) December 2016\n Sheila Williams, editor\n Cover art by NASA",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 5,
          name: 'One Story',
          issue: 'Issue #223: In the Neighborhood by Jess Rafalko',
          editor: 'Hannah Tinti',
          editor_url: 'http://cwp.as.nyu.edu/props/IO/35476/42/hannahtinti.jpg',
          edition: 'Kindle Edition',
          publication_date: '2016-12-20 0:00:01 UTC',
          pages: 36,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2016/12/223_cover-731x1024.png',
          description: "Twenty years ago, I loaded everything I owned into a truck and moved from a quiet place in the woods to the middle of New York City. It took nearly a year before I understood how to navigate the different subway lines, got used to Indian, Ethiopian, and Egyptian food (the three staples in my neighborhood), and learned how to sleep through the sirens outside my window at night. There is a feeling of disorientation that comes with moving to a completely new landscape, especially when it coincides with a great emotional change, as it does for the characters in Jess Rafalko’s marvelous short story, \“In the Neighborhood.\” Angela and Hank are a married couple who’ve moved from the flat-lands of Nebraska to the mountains of Vermont. They’ve unpacked and settled into new jobs, but the path of their journey is still strewn with wreckage. Hank is avoiding his grief and soldiering forward, while Angela has fallen into a well of guilt, anger, and sadness. Then, one day, a bear appears. The animal opens their mailbox, looking for food, and the scratches it leaves begin to tear down the walls that have built up between this husband and wife, who discover that moving to a new state may change the view from your window, but it will never change what’s in your heart. I hope you’ll all enjoy this story as much as our staff here at One Story did. And be sure to read Jess Rafalko’s Q&A with us, where she talks about work, love, loss, and the tornado that inspired this wonderfully moving story.",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 6,
          name: 'Asimov\'s Science Fiction',
          issue: 'January/February 2017 (Asimov\'s Science Fiction #492-493)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2017-01-01 0:00:01 UTC',
          pages: 212,
          img_url: 'https://images.gr-assets.com/books/1483662213l/33802402.jpg',
          description: "Novella\n \"The Speed of Belief\" by Robert Reed\n Novelettes\n \"Tagging Bruno\" by Alan M. Steele\n \"Fatherbond\" by Tom Purdom\n \"The Catastrophe of Cities\" by Lisa Goldstein\n \"The Meiosis of Cells and Exile\" by Octavia Cade\n Short Stories\n \"Crimson Birds of Small Miracles\" by Sean Monahan\n \“Still Life With Abyss\" by Jim Grimsley\n \"Winter Timeshare\" by Ray Nayler\n \"Pieces of Ourselves\" by Robert R. Chase\n \"Destination\" by Jack Skillingstead\n \"Starphone\" by Stephen Baxter\n \"Blow, Winds, and Crack your Cheeks\" by John Alfred Taylor\n Non-fiction\n Reflections: \"Two Cheers for Piltdown Man\" by Robert Silverberg\n Volume 41, Nos. 1&2 (#492&493) January/February 2017\n Sheila Williams, editor\n Cover art by Maurizio Manzieri",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 7,
          name: 'One Story',
          issue: 'Issue #224: Optimistic People by Chris Drangle',
          editor: 'Hannah Tinti',
          editor_url: 'http://cwp.as.nyu.edu/props/IO/35476/42/hannahtinti.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-01-17 0:00:01 UTC',
          pages: 36,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/01/224_cover.jpg',
          description: "There are many layers to Chris Drangle’s \“Optimistic People,\” including the layer of earth one of the characters is buried under as the story opens. Contributing Editor Will Allison lassoed this twisted, hair-raising work of fiction, so I’m happy to let him make the introductions. Enjoy!-PR\n This month we’re excited to bring you one of the most shocking, suspenseful short stories ever to cross One Story’s submission desk: \“Optimistic People,\” by Chris Drangle. Set in rural Virginia, “Optimistic People” is the tale of two teenagers on their first date. Warren and Soleil have plans to meet up in the woods to watch the sunset. Warren is well meaning but dim; as Soleil puts it, \“There was a thin line between being good and being a moron, and he straddled it.\” Soleil is the new, weird girl in town, her parents having fled Washington D.C. to escape a congressional staff assistant turned stalker.\n The teens’ plans go awry when Soleil runs out of gas en route to the meetup. Meanwhile, Warren stumbles upon two men burying a mysterious something in the woods. Minutes later, we meet friendly, disheveled Tom, whose prayers are answered when Warren unearths the pine box in which Tom has been buried alive.\n I’m guessing you’ve never encountered a character quite like Tom. (If there’s such a thing as your typical buried-alive guy, this guy is definitely not it.) I won’t spoil the plot by revealing more, but you should know that a man being buried alive is not this story’s most chilling plot twist. That comes later, and it unfolds in a fictional slow motion that will have you turning pages with a delicious sense of dread.\n Chris Drangle is still new on the literary scene, having published just a handful of stories, but we look forward to seeing a lot more of his work. You can get to know him in our online Q&A, where Chris discusses techniques of suspense, his fondness for story titles, and the importance of figuring out why the junebug collapses.",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 8,
          name: 'Asimov\'s Science Fiction',
          issue: 'March/April 2017 (Asimov\'s Science Fiction #494-495)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2017-02-19 0:00:01 UTC',
          pages: 190,
          img_url: 'https://images.gr-assets.com/books/1487341668l/34327347.jpg',
          description: "Novella\n \“Tao Zero\” by Damien Broderick\n Novelettes\n \"Soulmates.com\" by Will McIntosh\n \"Three Can Keep a Secret\" by Bill Johnson & Gregory Frost\n \"Kitty Hawk\" By Alan Smale\n \"The Wisdom of the Group\" by Ian R. McLeod\n Short Stories\n \"Number Thirty-Nine Skink\” by Suzanne Palmer\n \"The Ones Who Know Where They Are Going\" by Sarah Pinsker\n \“Invasion of the Saucer-Men\" by Dale Bailey\n \"Cupido\" by Rich Larson\n \"A Singular Event in the Fourth Dimension\" by Andrea M. Pawley\n \"After the Atrocity\" by Ian Creasy\n \"Goner\" by Gregory Norman Bossert\n \"We Regret the Error\" by Terry Bisson\n Poetry\n \"Mount Rushmore\" by Marge Simon\n \"Small Certainties\" by Sara Polsky\n \"Almost Certainly a Time Traveler\" by Jarod K. Anderson\n \"Surreal Axioms\" by Bruce Boston\n \"Note from Olympus Mons\" by Robert Frazier\n \"Rock, Paper, Scissors\" by Robert Borski\n Asimov's Science Fiction, March/April 2017, Volume 41, No. 3&4, #494-495\n Sheila Williams, editor\n Cover art by Tomislav Tikulin",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 9,
          name: 'New York Times',
          issue: 'Sunday, March 26, 2017',
          editor: 'Dean Baquet',
          editor_url: 'http://pixel.nymag.com/imgs/daily/intelligencer/2014/05/14/14-dean-baquet.w245.h368.2x.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-03-29 0:00:01 UTC',
          pages: 200,
          img_url: 'https://i.sixfoot6.org/images/nytimes-weight/nytimes-weight-lede.jpg',
          description: "The New York Times (sometimes abbreviated NYT and The Times) is an American daily newspaper, founded and continuously published in New York City since September 18, 1851, by The New York Times Company. The New York Times has won 119 Pulitzer Prizes, more than any other newspaper",
          created_at: new Date('2017-03-26 14:55:16 UTC'),
          updated_at: new Date('2017-03-26 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 10,
          name: 'One Story',
          issue: 'Issue #225: An Oral History of the Next Battle of the Sexes by Lucas Schaefer',
          editor: 'Hannah Tinti',
          editor_url: 'http://cwp.as.nyu.edu/props/IO/35476/42/hannahtinti.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-02-21 0:00:01 UTC',
          pages: 36,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/02/225_cover-copy-214x300.jpg',
          description: "When \“An Oral History of the Next Battle of the Sexes,\” by Lucas Schaefer, showed up at the office and I gave it an initial read, I spent the first few pages having to remind myself that I was reading a work of fiction and not an actual oral history. Once I wrapped my head around that, I became drawn in by one of the biggest casts of characters I’ve ever encountered in a short story—each voice distinctive, each character a building block in the recreation of a historic (fictitious) event: the legendary 1974 battle between Holly Hendrix and Terry Tucker. The story is as compelling as it is funny, as infused with personality as it is charged with spot-on observations about the way we regard gender, power, and ambition. We’re delighted to be ushering it into the world, and we’re even more delighted that this is the first publication by a talent we are most certainly going to be hearing more from in the future: Lucas Schaefer.\n To learn more about why Lucas chose to write a fictional oral history instead of a more traditional short story—and to hear what he has to say about the joys and challenges of that form—check out our online Q&A with the author. We make it standard practice to conclude our Q&As by asking authors to share the best piece of writing advice they’ve ever received. Lucas’s answer is both a charmer and heartbreaker!",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 11,
          name: 'One Story',
          issue: 'Issue #226: Prairie Fire, 1899 by Mike Alberti',
          editor: 'Hannah Tinti',
          editor_url: 'http://cwp.as.nyu.edu/props/IO/35476/42/hannahtinti.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-03-21 0:00:01 UTC',
          pages: 36,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/03/226_cover_blog-214x300.jpg',
          description: "When I was growing up in Florida, we would have tornados now and then. They were long and skinny, or fat and stubby, descending out of storm clouds to crack like a whip over our town, or poking down like the nose of a dog nudging a sand castle. The scariest thing about them—even scarier than their unpredictability—was their strength.\n I was reminded of those tornados when I first read Mike Alberti’s \“Prairie Fire, 1899.\” There are no tornados in this story, but, as the title suggests, there is a fire. A wide, merciless fire. And, as we all know, fires are merciless not because they don’t want to show mercy; they’re merciless because they’re single-minded. They only want one thing: to burn.\n The new issue of One Story is about the meeting of that fire and a mining community on the American frontier at the turn of the century. It has a classic, almost formal voice, and a narrator that moves from person to person with the ease of a spark carried on a breeze. In our Q&A, Mike Alberti describes it as “a sort of fable about the West.” It’s a remarkable, large-hearted short story with great staying power. We hope you enjoy it as much as we did.",
          created_at: new Date('2017-03-14 14:55:16 UTC'),
          updated_at: new Date('2017-03-22 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 12,
          name: 'New York Times',
          issue: 'Sunday, April 2, 2017',
          editor: 'Dean Baquet',
          editor_url: 'http://pixel.nymag.com/imgs/daily/intelligencer/2014/05/14/14-dean-baquet.w245.h368.2x.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-03-29 0:00:01 UTC',
          pages: 200,
          img_url: 'http://a341-47.so.clients.cdn13.com/wp-content/uploads/2017/03/5sNTboycMso.jpg',
          description: "The New York Times (sometimes abbreviated NYT and The Times) is an American daily newspaper, founded and continuously published in New York City since September 18, 1851, by The New York Times Company. The New York Times has won 119 Pulitzer Prizes, more than any other newspaper",
          created_at: new Date('2017-04-02 14:55:16 UTC'),
          updated_at: new Date('2017-04-02 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 13,
          name: 'New York Times',
          issue: 'Sunday, April 9, 2017',
          editor: 'Dean Baquet',
          editor_url: 'http://pixel.nymag.com/imgs/daily/intelligencer/2014/05/14/14-dean-baquet.w245.h368.2x.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-03-29 0:00:01 UTC',
          pages: 200,
          img_url: 'http://a341-47.so.clients.cdn13.com/wp-content/uploads/2017/03/5sNTboycMso.jpg',
          description: "The New York Times (sometimes abbreviated NYT and The Times) is an American daily newspaper, founded and continuously published in New York City since September 18, 1851, by The New York Times Company. The New York Times has won 119 Pulitzer Prizes, more than any other newspaper",
          created_at: new Date('2017-04-09 14:55:16 UTC'),
          updated_at: new Date('2017-04-09 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 14,
          name: 'Asimov\'s Science Fiction',
          issue: 'May/June 2017 (Asimov\'s Science Fiction #496-497)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2017-04-20 0:00:01 UTC',
          pages: 212,
          img_url: 'https://images.gr-assets.com/books/1493115502l/34923725.jpg',
          description: "CONTENTS\n\nNovella\n\"The Runabout\" by Kristine Kathryn Rusch\n\nNovelettes\n\"Come as You Are\" by Dale Bailey\n\"Night Fever\" by Will Ludwigsen\n\nShort Stories\n\"On the Ship\" by Leah Cypess\n\"Good Show\" by William Preston\n\"The Escape of the Adastra: Asha's Story\" by James Gunn\n\"Tired of the Same Old Quests?\" by Peter Wood\n\"The Best Man\" by Jay O'Connell\n\"Triceratops\" by Ian McHugh\n\"Persephone of the Crows\" by Karen Joy Fowler\n\nPoetry\n\"Sparking the Matter\" by Tod McCoy\n\"Your Clone Watches Over You\" by Robert Frazier\n\"Pinned\" by Suzanne Palmer\n\"Endeavor\" by G. O. Clark\n\nDepartments\n\"Editorial: Anniversaries and Milestones\" by Sheila Williams\n\"Reflections: Advertisements for Myself\" by Robert Silverberg\n\"On the Net: Harry and Dot\" by James Patrick Kelly\n\"On Books: Wolockification\" by Norman Spinrad\n\"SF Conventional Calendar\" by Erwin S. Strauss\n\nAsimov's Science Fiction, May/June 2017, Vol. 41, Nos. 5-6 (Whole Nos. 496-497)\nSheila Williams, editor\nCover art by ___",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 15,
          name: 'One Story',
          issue: 'Issue #227: What Is Behind by Tomiko Breland',
          editor: 'Patrick Ryan',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-04-20 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/04/227_cover-copy.jpg',
          description: "We at One Story aren’t in the habit of publishing stories that directly relate to current events—not because that’s our policy, but because such stories usually take a long time to dream up, percolate, and write. When Tomiko Breland’s “What Is Behind” came to us, we were captivated by the writing, first and foremost, and we were blown away by its immediate grasp of an ongoing, tragic, and very widespread current event: the plight of the Syrian refugees. The story follows nine people, inviting the reader into each of their heads as they emerge from hiding and make a run for safety. It’s a remarkable piece of political fiction—in no small part because its emotional impact is not just the result of the subject matter, but of the way it’s rendered. To read more about how the story came into existence, take a look at our Q&A with Tomiko Breland, where she reveals why the form she wrote in was the only one that allowed her to do justice to her characters.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 16,
          name: 'One Story',
          issue: 'Issue #228: The Third Birdhouse by John Biguenet',
          editor: 'Patrick Ryan',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-04-20 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/images/cover_os_228.png',
          description: "In one of the Old Testament’s more unsettling tales, God commands Abraham to sacrifice his only son, Isaac. The devout Abraham takes Isaac to a mountaintop, builds an altar, and binds his son to it. Just as Abraham raises his knife, though, an angel intervenes. \“Now I know you fear God,\” the angel says, “because you have not withheld from me your only son.” Abraham ends up killing a ram instead, and as a reward for his obedience, God blesses Abraham’s family.\n\nThings don’t work out quite so well for Abraham in \“The Third Birdhouse,\” John Biguenet’s contemporary retelling of Isaac’s life: it’s not okay in twentieth-century Brooklyn to try to murder your son with a hatchet, even if you think God told you to. But things do work out for the narrator, who—like the biblical Isaac—goes on to lead a long and prosperous life, with twin sons of his own.\n\nThe question is what kind of dad this modern Isaac will be, given the poor role model of Abraham. Isaac’s big test comes when his younger son, Jacob, swindles his twin brother out of his inheritance, just like in the Bible. How will Isaac respond? Raise the hatchet? Bury the hatchet? Hatch a compromise? His solution surprised me, and it’s one I’m still grappling with, which is partly why I love this story: like all good literature, it challenges the reader, posing questions rather than answering them.\n\nJohn Biguenet, on the other hand, was more than happy to answer our questions. Be sure to check out his author interview to learn how birdhouses found their way into this retelling of Isaac’s story and to get John’s distinctive take on the reading habits of Donald Trump.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 17,
          name: 'Asimov\'s Science Fiction',
          issue: 'July/August 2017 (Asimov\'s Science Fiction #498-499)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2017-06-20 0:00:01 UTC',
          pages: 212,
          img_url: 'https://images.gr-assets.com/books/1498657935l/35486990.jpg',
          description: "FORTIETH ANNIVERSARY YEAR\nYou’ll find two fast-paced novellas in Asimov’s July/August 2017 issue. In \“How Sere Picked Up Her Laundry,\” Alexander Jablokov reveals that much is going on beneath the surface in this endlessly inventive tale. Exterminators, dangerous aliens, internecine business deals, a nosy detective, and laundry all come into play in a tale about a planet full of mysteries. Adventure also abounds with abductions, civil war, and spaceships in R. Garcia y Robertson’s hurtling story about \“The Girl Who Stole Herself.\” You won’t want to miss either of these enthralling tales!\n\nALSO IN JULY/AUGUST\nRudy Rucker & Marc Laidlaw return to Asimov’s with a wacky new story about how a couple of surfer dudes discover the secret of \“@lantis\”; James Gunn introduces us to a couple of pilgrims with ulterior motives as his series continues with \“Transcendental Mission: Riley’s Story\” and \“Weighty Matters: Tordor’s Story\"; new author Cadwell Turnbull spins a poignant tale about \“Other Worlds and This One\”; while Lisa Goldstein offers a disturbing glimpse of the future in \“Annabelle, Annie\”; \“The Patient Dragon\” calmly bides its time in David Gerrold’s new short thriller; Sheila Finch conducts some heartbreaking \“Field Studies\”; Michael Bishop introduces us to the enigmatic \“Gale Strang\”; and get ready for more tension and intrigue when you and Rich Larson spend \“An Evening with Severyn Grimes.\”\n\nOUR EXCITING FEATURES\nRobert Silverberg’s Reflections column contemplates collaborative SF writers \“Sharing Worlds\”; James Patrick Kelly’s On the Net commands us to \“Hold the Phones!\”; Paul Di Filippo’s On Books considers new works from Robert Silverberg, Carrie Vaughn, Connie Willis, Rick Wilber, and others; plus we’ll have an array of poetry and other features you’re sure to enjoy. Look for our super-stuffed May/June issue on sale at newsstands on June 20, 2017. Or subscribe to Asimov’s in print or in a wide variety of digital formats.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 18,
          name: 'One Story',
          issue: 'Issue #229: Goodnight Nobody by Sarah Hall',
          editor: 'Patrick Ryan',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-04-20 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/images/cover_os_229.png',
          description: "Meet Jem, an eleven-year-old girl who is leaning forward toward adulthood with all her might. She has, as the author describes it in our Q&A, “an elastic, skipping-ahead brain” that doesn’t necessarily want to focus on the little brother she’s often charged with watching, that would much rather be investigating the bloody incident that has taken place down the street—an incident that’s left one person dead and put another person in jail. (Her brain would also like to be watching Thundercats, but that’s not an option at present.)\n\nSarah Hall, the author of “Goodnight Nobody,” is one of the most careful writers I know. Her word choices, narrative pacing, and sentence rhythm are the result, I suspect, of a great deal of hard, obsessive work. And yet none of that calls attention to itself. The nuts, bolts, and machinery are all hidden away, and her work is a pleasurable breeze to read. One of the great achievements of this particular story is the fact that its voice is so intimately attached to Jem, it feels as if it’s written in the first-person. I find \“Goodnight Nobody\” to be an addictive read, and I hope you do too.\n\nIf, by chance, you haven’t encountered Sarah Hall’s work before (she now has two story collections and five novels under her belt), I’m all the happier to be introducing you to her. Her new story collection is called Madame Zero. She’s a treasure, and we’re honored to have her in the One Story family.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 19,
          name: 'One Story',
          issue: 'Issue #230: Bayou by Bryan Washington',
          editor: 'Patrick Ryan',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-07-25 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/images/cover_os_230.png',
          description: "When I was ten years old, I saw a movie called The Mysterious Monsters. It was about Bigfoot, the Loch Ness Monster, and the Abominable Snowman, and it was filled with cheesy “reenactments” of personal testimonies about encounters with these mythical creatures. Because it was presented as a documentary, and because I was ten, I watched the reenactment footage in absolute horror, completely forgetting these were actors (including the guy in the Bigfoot costume). For the next year, I had a hard time falling asleep, convinced that Bigfoot was going to crash a hairy arm through my bedroom window. I also spotted Bigfoot any time I got near nature—at least a dozen sightings by the time I turned eleven.\n\nThe two friends in Bryan Washington’s short story “Bayou” aren’t boys; they’re young men. When they discover a strange creature near a bayou on the outskirts of Houston, it isn’t fear they feel so much as a burnt-out sense of wonder, and maybe a chance to make some money. I was immediately drawn to “Bayou” because it begins with a chupacabra, and while many people claim to have encountered chupacabras (and even filmed them), biologists refuse to confirm their existence. So I was hooked from the get-go. But what follows is more than a monster story. It’s a story about friendship, misunderstanding, and longing. Or, as the author puts it in our Q&A, it’s a story about intimacy. I hope you enjoy it as much as I did, and if it inspires your own sighting of a mysterious monster—so long as it’s not a Bigfoot—I look forward to the reenactment.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 20,
          name: 'Asimov\'s Science Fiction',
          issue: 'September/October 2017 (Asimov\'s Science Fiction #500-501)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2017-08-22 0:00:01 UTC',
          pages: 212,
          img_url: 'https://images.gr-assets.com/books/1504371081l/36067380.jpg',
          description: "Powerful novelettes bookend Asimov’s September/October 2017 issue. Sarah Pinsker’s lyrical tale set aboard a generation ship shows us that humanity may have the strength to adapt and evolve as long as “Wind Will Rove.” All that lies between civilization and brutal marauders is an outcast and a library in Suzanne Palmer’s thrilling “Books of the Risen Sea.”\n\nFall is here, which means the September/October issue has its share of slightly spooky tales: Kit Reed investigates the “Disturbance in the Produce Aisle”; Carrie Vaughn introduces us to “Dead Men in Central City”; Sandra McDonald demonstrates the peril of “Riding the Blue Line With Jack Kerouac”; and William Preston unlocks “The Cabinet.” We learn that it may not be wise to open Michael Swanwick’s “Universe Box”; discover why “Squamous and Eldritch Get a Yard Sale Bargain” in Tim McDaniel’s short story; and climb “The Fourth Hill’ with new author Dennis E. Staples; On the nonspooky side, “Arriving at Terminal: Xi’s Story” and “The Ganymede Gambit: Jan’s Story” reveal the secrets of two more pilgrims in James Gunn’s intriguing series; Harry Turtledove brings us the deeply disturbing tale of the “Zigeuner”; Allen M. Steele returns with a cryptic account of “An Incident in the Literary Life of Nathan Arkwright”; and far flung action continues in R. Garcia y Robertson’s “Grand Theft Spaceship.”\n\nRobert Silverberg’s Reflections column examines the end of empires and the plight of “The Last Hittite”; James Patrick Kelly’s On the Net spends time “Remembering Bertie”; Norman Spinrad’s On Books considers locations “Outside America” as he traverses works by Bruce Sterling, Nnedi Okarafor, Lavie Tidhar, and Indra Das; plus we’ll have an array of poetry and other features you’re sure to enjoy.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 21,
          name: 'One Story',
          issue: 'Issue #231: Please Give Me One Good Reason Not to Hate You by Shawn Vestal',
          editor: 'Patrick Ryan',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-07-25 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/images/cover_os_231.png',
          description: "“I arrived in Bozeman after the place that came after Animas, was thinking I would stay forever—thinking I would finally stop what I’ve been doing and be someone, thinking this place was really me.” So says Benny, the semi-likable sleazeball who narrates Shawn Vestal’s brilliant new story “Please Give Me One Good Reason Not to Hate You.”\n\nThe thing is, Benny isn’t really his name. “Benny” is just the latest in a string of identities he has fashioned as a small-time scam artist crisscrossing the American West. Also, it’s not just the scams that keep Benny on the move. It’s people—his overpowering need to be among them and apart from them. You might say Benny is alternately addicted to and allergic to his fellow man. It’s an internal tug-of-war that so far has guaranteed him a life of perpetual unfulfillment.\n\nBut Bozeman—beautiful Bozeman, Montana—is going to be different. Bozeman is the place, Benny comes to believe, where he’ll finally settle down, fit in, and take a chance on normal human happiness. To that end, despite being out of shape and hopelessly un-outdoorsy, Benny accepts an invitation to go on a four-day, forty-four-mile mountain hike with a quartet of hip thirty-somethings—including his sort-of ex-girlfriend and her new boyfriend.\n\nIf that sounds like a bad idea, you’re right, especially given Benny’s gift for self-sabotage. It doesn’t help that he’s a liar, a criminal, and a misanthrope. But whether you end up rooting for Benny or against him, we think you’ll agree that his story is one of the funniest, most compelling, and most daringly original works to grace our pages.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 22,
          name: 'Asimov\'s Science Fiction',
          issue: 'November/December 2017 (Asimov\'s Science Fiction #502-503)',
          editor: 'Sheila Williams',
          editor_url: 'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png',
          edition: 'Kindle Edition',
          publication_date: '2017-10-22 0:00:01 UTC',
          pages: 212,
          img_url: 'https://images.gr-assets.com/books/1508496139l/36445259.jpg',
          description: "CONTENTS\n\nNovella\n\"I Met a Traveller in an Antique Land\" by Connie Willis\n\nNovelettes\n\"The Discrete Charm of the Turing Machine\" by Greg Egan\n\"In Dublin, Fair City\" by Rick Wilber\n\"Nine Lattices of Sargasso\" by Jason Sanford\n\nShort Stories\n\"Confessions of a Con Girl\" by Nick Wolven\n\"The Last Dance\" by Jack McDevitt\n\"And No Torment Shall Touch Them\n\" by James Patrick Kelly\n\"Timewalking\" by Michael Cassutt\n\"Skipped\" by Emily Taylor\n\"Afloat Above a Floor of Stars\" by Tom Purdom\n\"Love and Death and the Star That Shall Not Be Named: Kom's Story\" by James Gunn\n\"Operators\" by Joel Richards\n\"The Nanny Bubble\" by Norman Spinrad\n\nPoetry\n\"Apocatastasis\" by Jennifer Crow\n\"Your Clone Authors a Sticky Note\" by Robert Frazier\n\"Change State\" by Ken Poyner\n\"Probabilities\" by G.O. Clark\n\"Nettle Coat\" by Jane Yolen\n\"How to Die on a Faraway Planet\" by H. Mellas\n\"A Myth as Big as a Mile\" by Jane Yolen\n\nDepartments\n\"Editorial: Excelsior!\" by Sheila Williams\n\"Reflections: Gog and Magog\" by Robert Silverberg\n\"On the Net: Time Party\" by James Patrick Kelly\n\"On Books\" by Peter Heck\n\"SF Conventional Calendar\" by Erwin S. Strauss\n\nAsimov's Science Fiction, November/December 2017, Vol. 41, Nos. 11-12 (Whole Nos. 502-503)\nSheila Williams, editor\nCover art by [TBD]",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 23,
          name: 'One Story',
          issue: 'Issue #232: A Month on Greene Street by Tom Hanks',
          editor: 'Patrick Ryan',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-10-15 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/09/a-month-on-greene-street-cover-copy.jpg',
          description: "I’ve long been guilty of inaccurate first impressions. Thankfully, I usually keep them to myself—just private little assessments I make of, say, a person I see across a room. Observations I deem both intuitive and astute. What an accurate judge of character I am! I can sum you up with a glance or, at the very most, a few seconds of watching your mannerisms, your facial expressions. That’s how sharp my receptors are.\n\nOnly, they aren’t that sharp. Sometimes I’m near the mark; quite often I’m way off. “Always trust your first impression” is advice we’ve all heard before, and it’s often true—but it slams up against “Don’t judge a book by its cover,” “Don’t knock it till you try it,” and even “Proof’s in the pudding.”\n\nOur new issue is a story called “A Month on Greene Street,” and it’s about a woman named Bette who has just moved her family into a new house. Not only does Bette rely heavily on first impressions, she also takes great stock in what she considers to be her extrasensory visions, or “pops” (as she calls them). “Pops” are little glimpses of the future Bette has now and then. Sometimes they come true; sometimes they don’t. They’re a source of comfort; they’re a source of worry. And there are quite a few of them to be had in a new home, on a new street, surrounded by new neighbors.\n\nThis story won me over the first time I read it, and upon each subsequent reading it becomes more layered, more moving, and funnier. It’s written by an author we already know to be a tremendously accomplished actor, and the fact that he’s now proving himself to be a tremendously talented writer of short stories makes me wonder what else he can do. (Levitate? Bend things with his mind?) One Story is thrilled to be giving the world its first glimpse of “A Month on Greene Street” by Tom Hanks. Be sure to check out our Q&A with the author, wherein he discusses Bette, her pops, why and how he came to write short stories, and his fondness for the good old-fashioned typewriter.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 24,
          name: 'One Story',
          issue: 'Issue #233: Are You Mine and No One Else’s by Danny Lorberbaum',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-11-15 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/10/cover-blog-copy.jpg',
          description: "One of best things about reading short stories and novels is that we get to spend time with people we wouldn’t actually want to know. This applies to out-and-out villains, of course, but it also applies to jerks, narcissists, bigots, whiners, chronic interrupters, what have you. Spending time with such types via the written word is great not only because we get to observe them without having to be in the same room with them, but also because we get a chance to be in their heads for a little while and better understand what it’s like to be them. The feeling may only last for as long as your eyes are moving across the page, but there it is: empathy, no strings attached.\n\nOur new issue takes us into the heads of two different characters—Rhoda and Tony—and I’m guessing you might not want to be besties with one of them. You will, however, be on intimate terms with both of them by the last sentence, and I wager you’ll see a little of yourself somewhere along the way. Mix longing with possessiveness, desire with performance anxiety, second-guessing with secret-keeping, skinny-dipping with fast driving, and project it all onto a backdrop of America in the early days of the Reagan administration, and you’ve got “Are You Mine and No One Else’s?” by emerging writer Danny Lorberbaum.\n\nThe goal of One Story, first and foremost, is to put great short stories into readers’ hands. Along the way, we often make readers aware of writers they might not yet have come across. I’m confident Danny Lorberbaum is at the beginning of a vast and varied career, and I’m thrilled to be sending you “Are You Mine and No One Else’s?”—a story I find as charming as it is unsettling. To read our Q&A with the author (and to hear about the news story that caused seven-year-old Danny to reassess the world), please visit our website.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        }),
        knex('periodicals').insert({
          id: 25,
          name: 'One Story',
          issue: 'Issue #234: The Crazies by Maud Streep',
          editor_url: 'https://www.one-story.com/blog/wp-content/uploads/2013/06/PRyan.jpg',
          edition: 'Kindle Edition',
          publication_date: '2017-11-24 0:00:01 UTC',
          pages: 39,
          img_url: 'https://www.one-story.com/blog/wp-content/uploads/2017/10/234-cover-copy.jpg',
          description: "This month’s story, “The Crazies,” was found and edited by contributing editor Will Allison, so I’m happily turning the steering wheel over to him to guide us in. — PR\n\nAs many a cowboy ballad can tell you, the halo glow of new love never lasts. Sometimes it simmers down with age; sometimes it flames into something else; and sometimes it just flickers out. It’s one of those lessons we all learn sooner or later.\n\nEven so, when I read “The Crazies” by Maud Streep, I couldn’t help but be charmed by the halo glow of its early pages. The narrator, a recent Yale grad, heads to Montana, takes a job at a Wild West tourist attraction, and falls in love with a cowboy named Jake. Their marriage is a happy whirlwind of cheap beer, sex, optimism, and simple, carefree living.\n\nBut halfway through the story, the couple’s happiness turns to anguish. At the risk of giving away too much: something terrible happens on an elk hunting trip in The Crazy Mountains, and the narrator and Jake may or may not be responsible. How each of them deals with this possibility will determine whether their love endures, or whether it flickers out.\n\n“The Crazies” is wise about life and relationships in ways one would expect from a veteran storyteller. As it happens, though, this is Maud Streep’s first published story. We are very pleased to present One Story’s second debut of 2017, and we hope you are as crazy about “The Crazies” as we are.\n\nVisit the One Story website to read our Q&A with the author.",
          created_at: new Date('2017-04-21 14:55:16 UTC'),
          updated_at: new Date('2017-04-21 14:55:18 UTC')
        })
      ]);
    })
    .then(() => {
      return knex.raw("SELECT setval('periodicals_id_seq', (SELECT MAX(id) FROM periodicals));");
    });
};
